dbt_modelling:
  outputs:
    dev:
      account: CEAADZV-SZ01970
      database: AIRBNB
      password: 8762N54xzU8FdCj
      role: ACCOUNTADMIN
      schema: BRONZE
      threads: 1
      type: snowflake
      user: Ajibola
      warehouse: COMPUTE_WH
  target: dev
